name: bored
description: when you are bored to use discussions or reddit you can just write here
labels: ["Bug", "Needs Triage"]
body:
- type: markdown
  attributes:
    value: "## bored to do that, but for questions in case you cant use the discussion"
- id: description
  type: textarea
  validations:
    required: true
  attributes:
    label: '📍 text'
    description: |
            boring
    placeholder: |
      put a text here
